version: 0.2

env:
  parameter-store:
    GITHUB_TOKEN: GITHUB_TOKEN 
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - export REPO="${repository_name}"
      - export TERRAFORM_WORKSPACE="${tf_workspace}"
      - . ./buildspecs/buildspec-plan.sh
artifacts:
  files: # globstar because almost everything we have, we need
    - '**/*'
